name: build-and-package

on:
  push:
    tags:
      - "*"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    container: 
      image: atom63/qt-docker:linux-buster-x86_64-qt5
      options: --user root

    steps:
      - name: Clone this repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential tree 

      - name: Build and package
        run: |
          make package

      - name: Build Appimage
        run: |
          make linuxdeploy
          make genrate-appimage

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: |
            build/*.deb
            build/*.Appimage

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: |
            build/*.deb
            build/*.Appimage
          body: |
            This is the first release.
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}