name: build-and-package

on:
  push:
    tags:
      - "*"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y debhelper devscripts qt5-default

      - name: Build and package
        run: |
          make package

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: build/*.deb

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            This is the first release.
          draft: false
          prerelease: false