name: build-and-package

on:
  push:
    tags:
      - "*"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    container: docker://atom63/qt-docker:linux-buster-x86_64-qt5

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential


      - uses: actions/checkout@v2
      - name: Build and package
        run: |
          make package

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: build/*.deb

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          body: |
            This is the first release.
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}